# Generated by Django 3.0.6 on 2020-05-22 15:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_virtual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.FloatField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Entity')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('app.entity',),
        ),
        migrations.CreateModel(
            name='Future',
            fields=[
                ('commodity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Commodity')),
                ('strike_price', models.FloatField()),
                ('action_date', models.DateTimeField()),
            ],
            bases=('app.commodity',),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Entity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.entity',),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('reason', models.TextField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_transactionhistory_to', to='app.Entity')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_transactionhistory_from', to='app.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='ShareSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_sharesnapshot_athlete', to='app.Athlete')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_sharesnapshot_owner', to='app.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_processed', models.DateTimeField(auto_now_add=True)),
                ('next_payment_due', models.DateTimeField()),
                ('interest_rate', models.FloatField()),
                ('balance', models.FloatField()),
                ('repayment_interval', models.DurationField(default=datetime.timedelta(7))),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_loan_lender', to='app.Entity')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_loan_recipient', to='app.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
                ('has_been_distributed', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_dividend_athlete', to='app.Athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ammount', models.FloatField()),
                ('owed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_debt_owed_by', to='app.Entity')),
                ('owed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_debt_owed_to', to='app.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_commodity_owner', to='app.Entity'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('future_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Future')),
                ('current_option', models.BooleanField(default=True)),
            ],
            bases=('app.future',),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('decision_dt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Cancelled')], default='P', max_length=1)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_trade_buyer', to='app.Entity')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_trade_commodity', to='app.Commodity')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_trade_seller', to='app.Entity')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_trade_creator', to='app.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('commodity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Commodity')),
                ('a_to_b_payment', models.TextField()),
                ('b_to_a_payment', models.TextField()),
                ('party_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_swap_partya', to='app.Investor')),
                ('party_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_swap_partyb', to='app.Investor')),
            ],
            bases=('app.commodity',),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('commodity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Commodity')),
                ('volume', models.FloatField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_share_athlete', to='app.Athlete')),
            ],
            bases=('app.commodity',),
        ),
    ]
