# Generated by Django 3.0.6 on 2020-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investor",
            name="uitheme",
            field=models.CharField(
                choices=[
                    ("L", "light"),
                    ("D", "dark"),
                    ("O", "oxford"),
                    ("C", "cambridge"),
                ],
                default="L",
                max_length=1,
            ),
        ),
    ]
