# Generated by Django 3.0.6 on 2020-06-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracthistory',
            name='asset',
        ),
        migrations.AddField(
            model_name='contracthistory',
            name='contract',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Contract'),
            preserve_default=False,
        ),
    ]
