# Generated by Django 3.0.6 on 2020-05-31 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bank',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Bank'),
            preserve_default=False,
        ),
    ]
