# Generated by Django 3.0.6 on 2020-06-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200602_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='future',
            name='settled',
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('U', 'Unsold'), ('A', 'Active'), ('S', 'Settled'), ('V', 'Void')], default='U', max_length=1),
        ),
    ]
