# Generated by Django 3.0.6 on 2020-05-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auction_bank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('bidder', 'lot')},
        ),
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
    ]
