# Generated by Django 3.0.6 on 2020-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_investor_uitheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investor",
            name="uitheme",
            field=models.CharField(
                choices=[
                    ("L", "Light"),
                    ("D", "Dark"),
                    ("O", "Oxford"),
                    ("C", "Cambridge"),
                ],
                default="L",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="event_details_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="race",
            name="results_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
