# Generated by Django 3.0.6 on 2020-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20200530_1814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="result",
            name="dividend",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="result",
            name="time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
