# Generated by Django 3.0.6 on 2020-06-03 23:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200603_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.FloatField()),
                ('repayment_interval', models.DurationField(default=datetime.timedelta(7))),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bank')),
            ],
        ),
    ]
