# Generated by Django 3.0.6 on 2020-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200531_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
