# Generated by Django 3.0.6 on 2020-05-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auction_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='team_last_year',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
