# Generated by Django 3.0.6 on 2020-06-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200610_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankoffer',
            name='total_price',
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='total_buy_price',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='total_sell_price',
            field=models.FloatField(default=-1),
        ),
    ]
