# Generated by Django 3.0.6 on 2020-05-31 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200531_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Season'),
            preserve_default=False,
        ),
    ]
