# Generated by Django 3.0.6 on 2020-05-31 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_transactionhistory_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareindexvalue',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Season'),
            preserve_default=False,
        ),
    ]
