# Generated by Django 3.0.6 on 2020-06-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_shareownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='recipient_capital',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='sender_capital',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
