# Generated by Django 3.0.6 on 2020-06-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_shareindexvalue_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='underlying_asset',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.Share'),
            preserve_default=False,
        ),
    ]
