# Generated by Django 3.0.6 on 2020-06-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200614_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_option_option_holder', to='app.Entity'),
            preserve_default=False,
        ),
    ]
