# Generated by Django 3.0.6 on 2020-06-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200601_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='future',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='future',
            name='seller',
        ),
        migrations.AddField(
            model_name='future',
            name='other_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_future_other_party', to='app.Entity'),
        ),
        migrations.AddField(
            model_name='future',
            name='owner_obligation',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1),
        ),
    ]
