# Generated by Django 3.0.6 on 2020-06-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200601_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
