# Generated by Django 3.0.6 on 2020-06-01 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_future_settled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Investor')),
            ],
        ),
    ]
