# Generated by Django 3.0.6 on 2020-06-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('U', 'Unseen'), ('S', 'Seen'), ('D', 'Dismissed')], default='U', max_length=1),
        ),
    ]
