# Generated by Django 3.0.6 on 2020-06-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200616_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='current_option',
            field=models.BooleanField(default=True),
        ),
    ]
