# Generated by Django 3.0.6 on 2020-06-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200616_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankoffer',
            name='total_buy_price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bankoffer',
            name='total_sell_price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bankoffer',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price_per_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='debt',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entity',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='future',
            name='strike_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Fractional interest rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Fractional interest rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lot',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='race',
            name='max_dividend',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='race',
            name='min_dividend',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='dividend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='recipient_capital',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='sender_capital',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
