# Generated by Django 3.0.6 on 2020-06-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_trade_decision_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='future',
            old_name='action_date',
            new_name='strike_time',
        ),
    ]
