# Generated by Django 3.0.6 on 2020-07-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200619_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='other_party',
        ),
        migrations.RemoveField(
            model_name='future',
            name='owner_obligation',
        ),
        migrations.AddField(
            model_name='share',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_share_owner', to='app.Entity'),
        ),
    ]
