# Generated by Django 3.0.6 on 2020-07-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200704_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_future_buyer', to='app.Entity'),
        ),
        migrations.AddField(
            model_name='future',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_future_seller', to='app.Entity'),
        ),
    ]
