# Generated by Django 3.0.6 on 2020-07-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200704_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracthistory',
            old_name='owner',
            new_name='party_a',
        ),
    ]
